name: EAS Build and Deploy

# This workflow builds and deploys the app using EAS
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - preview
          - production

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build for Android
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas build --platform android --profile develop --non-interactive

      - name: Build for iOS
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas build --platform ios --profile develop --non-interactive

      - name: Deploy Update
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas update --channel develop --message "Automated update from GitHub Actions" --non-interactive 